export const ICONS = {
  "clear-day": "☀️",
  "clear-night": "🌙",
  thunderstorm: "⛈️",
  rain: "🌧️",
  snow: "❄️",
  sleet: "🌨️",
  wind: "💨",
  fog: "🌫️",
  cloudy: "☁️",
  "partly-cloudy-day": "⛅",
  "partly-cloudy-night": "☁️",
  hail: "🌨️",
  "mostly-clear-day": "🌤️",
  "mostly-clear-night": "🌙",
  "mostly-cloudy-day": "🌥️",
  "mostly-cloudy-night": "☁️",
  "possible-rain-day": "🌦️",
  "possible-rain-night": "🌧️",
  "possible-snow-day": "🌨️",
  "possible-snow-night": "🌨️",
  "possible-sleet-day": "🌨️",
  "possible-sleet-night": "🌨️",
  "possible-precipitation-day": "🌦️",
  "possible-precipitation-night": "🌧️",
  "possible-thunderstorm-day": "⛈️",
  "possible-thunderstorm-night": "⛈️",
  precipitation: "🌧️",
  drizzle: "🌦️",
  "light-rain": "🌦️",
  "heavy-rain": "🌧️",
  flurries: "🌨️",
  "light-snow": "🌨️",
  "heavy-snow": "❄️",
  "very-light-sleet": "🌨️",
  "light-sleet": "🌨️",
  "heavy-sleet": "🌨️",
  breezy: "💨",
  "dangerous-wind": "💨",
  mist: "🌫️",
  haze: "🌫️",
  smoke: "🌫️",
  mixed: "🌫️",
} as const;

export const CARD_STYLE = "hover:bg-card/65 transition";
